dist: trusty
sudo: false
language: cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty-5.0
    packages:
      - g++-6
      - clang-5.0
      - sudo add-apt-repository -y ppa:team-xbmc/ppa
      - sudo apt-get update -qq
      - sudo apt-get install -y  libsdl2-dev
before_install:
  - pip install --user cpp-coveralls

script:
  - CXX=/usr/bin/g++-6 CC=/usr/bin/gcc-6 cmake -DCOVERAGE=1 .
  - cmake --configure .
  - cmake --build .
  - ./Tests

after_success:
  - coveralls --root . -E ".*CMakeFiles.*"