dist: trusty
language: cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty-5.0
    packages:
      - g++-6
      - clang-5.0
      - libsdl2-2.0-0
      - libsdl2-dev
      - libsdl2-gfx-dev
      - libsdl2-image-2.0-0
      - libsdl2-image-dev
      - libsdl2-mixer-2.0-0
      - libsdl2-net-2.0-0
      - libsdl2-net-dev
      - libsdl2-ttf-2.0-0
      - libsdl2-ttf-dev


before_install:
  - pip install --user cpp-coveralls

script:
  - CXX=/usr/bin/g++-6 CC=/usr/bin/gcc-6 cmake -DCOVERAGE=1 .
  - cmake --configure .
  - cmake --build .
  - ./Tests

after_success:
  - coveralls --root . -E ".*CMakeFiles.*"